export const SET_AUTHORIZATON = 'SET_AUTHORIZATON';
export const GET_ALL_DOCTORS = 'GET_ALL_DOCTORS';
export const GET_ALL_CLINICS = 'GET_ALL_CLINICS';
export const SET_APPOINMENT_DOCTOR = 'SET_APPOINMENT_DOCTOR';
export const SET_USER = 'SET_USER';
export const FILTER_DOCTORS = 'FILTER_DOCTORS';